#include "StdAfx.h"
#include "AssignmentExpression.h"
#include "StringHelper.h"


AssignmentExpression::AssignmentExpression(void)
{
	Type=Assignment;
}


AssignmentExpression::~AssignmentExpression(void)
{
}

string AssignmentExpression::ToString(int nestLevel)
{
	string str;
	for(int i=0;i<nestLevel;i++)
	{
		str.append("    ");
	}

	string leftString = leftExpression->ToString();
	if(leftString.compare("$L.comments.AutoGenerated.byEDITOR") ==0)
	{
		str.append("//");
		str.append(StringHelper::UnescapeString(rightExpression->ToString()));
	}
	else
	{
		str.append(leftString);
		str.append(" ");
		str.append(signToken.GetTokenValue());
		str.append(" ");
		str.append(rightExpression->ToString());
	}
	return str;
}

string AssignmentExpression::ToString()
{
    string str;
	str.append(leftExpression->ToString());
	str.append(" ");
	str.append(signToken.GetTokenValue());
	str.append(" ");
    str.append(rightExpression->ToString());
    return str;
}