#include "StdAfx.h"
#include "CommentsStatement.h"
#include "StringHelper.h"

CommentsStatement::CommentsStatement(void)
{
	Type=Comments;
}

CommentsStatement::~CommentsStatement(void)
{

}


RadToken CommentsStatement::GetToken()
{
	return token;
}
void CommentsStatement::SetToken(RadToken& radToken)
{
	token = radToken;
}
string CommentsStatement::ToString(int nestLevel)
{
	string str;

	for(int i=0;i<nestLevel;i++)
	{
		str.append("    ");
	}

	str.append("//");
	str.append(token.GetTokenValue());

	return str;
}
string CommentsStatement::ToString()
{
	string str;

	str.append("$L.comments.AutoGenerated.byEDITOR=\"");
	str.append(StringHelper::EscapeString(token.GetTokenValue()));
	str.append("\"");

	return str;
}